spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_manor?serverTimezone=GMT&useUnicode=true&characterEncoding=utf8
    #cloud_manor?serverTimezone=GMT&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 1
    host: 47.94.236.46
    port: 6379
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.buba.cloud.cloudManor.pojo
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true
#打印sql
logging:
  level:
    com.buba.cloud.cloudManor.mapper: debug

server:
  port: 8080


