spring:
  datasource:
    url: jdbc:mysql://123.56.254.245:3306/cloud_manor?serverTimezone=GMT&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 1
    host: 123.56.254.245
    port: 6800
  http:
    multipart:
      maxFileSize: 5MB
      maxRequestSize: 30MB
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.buba.cloud.cloudManor.pojo
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true
#打印sql
logging:
  level:
    com.buba.cloud.cloudManor.mapper: debug

server:
  port: 8088


